version: "3.3"

services:
    redis:
        container_name: redis
        image: redis:alpine
        restart: on-failure
        networks:
            - hyperion
        ports:
            - 6379:6379

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        restart: on-failure
        environment:
            - RABBITMQ_DEFAULT_USER=username
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_DEFAULT_VHOST=/hyperion
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - hyperion

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        restart: on-failure
        environment:
            - discovery.type=single-node
            - cluster.name=es-cluster
            - node.name=es01
            - bootstrap.memory_lock=true
            - xpack.security.enabled=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - ELASTIC_USERNAME=elastic
            - ELASTIC_PASSWORD=password
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - hyperion

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.6
        restart: on-failure
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=password
        ports:
            - 5601:5601
        networks:
            - hyperion
        depends_on:
            - elasticsearch

    hyperion-indexer:
        container_name: hyperion-indexer
        image: sweatpotato/hyperion-history-api:3.3.9
        restart: on-failure
        depends_on:
            - elasticsearch
            - redis
            - rabbitmq
        volumes:
            - ./config/connections.json:/hyperion-history-api/connections.json
            - ./config/ecosystem.config.js:/hyperion-history-api/ecosystem.config.js
            - ./config/chains/:/hyperion-history-api/chains/
            - ./scripts/:/home/hyperion/scripts/
        networks:
            - hyperion
        command: sh -c "/home/hyperion/scripts/run-hyperion.sh ${SCRIPT:-false} eos-indexer"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    hyperion-api:
        container_name: hyperion-api
        image: sweatpotato/hyperion-history-api:3.3.9
        restart: on-failure
        ports:
            - 7010:7000
        depends_on:
            - hyperion-indexer
        volumes:
            - ./config/connections.json:/hyperion-history-api/connections.json
            - ./config/ecosystem.config.js:/hyperion-history-api/ecosystem.config.js
            - ./config/chains/:/hyperion-history-api/chains/
            - ./scripts/:/home/hyperion/scripts/
        networks:
            - hyperion
        command: sh -c "/home/hyperion/scripts/run-hyperion.sh ${SCRIPT:-false} eos-api"
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    hyperion:
        driver: bridge
